#!/bin/sh -e

base_version=1.4.0
version="$base_version+git`date +%Y%m%d%H%M`"

tmp_dir="/tmp/cruisecontrol.rb.git"
sources_dir="$tmp_dir/cruisecontrolrb-$base_version"

rm -rf $tmp_dir
mkdir -p $tmp_dir

git clone git://github.com/thoughtworks/cruisecontrol.rb.git $sources_dir
rm -rf $sources_dir/.git

tar -czf "cruisecontrolrb-$version.tgz" -C $tmp_dir .

dch --newversion "$version-0" 'New upstream release'